### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by shixin-guo** [ycwalker/CMS-of-Blog#10]
按照说明下载安装 跑npm run build 时候

![image](https://cloud.githubusercontent.com/assets/12186221/22692008/df74a28e-ed77-11e6-83e0-31f6d60a3ce3.png)

**Comment by ciqulover** [comment]
谢谢指出错误，这是由extract-text-webpack-plugin升级引起的：
 https://github.com/vuejs/vue-loader/issues/624
已在`package.json`更新依赖：https://github.com/ycwalker/CMS-of-Blog/commit/d62a70c712096877795b6c29c007731cafde3273

**Comment by shixin-guo** [comment]
我也是想研究研究 学习一下 还是得谢谢你开源出来 供我们学习
