### ISSUE TITLE
hello，请教一个问题^_^

### ISSUE THREAD

**Issue by rudyxu1102** [ycwalker/CMS-of-Blog#12]
不明白为什么Article.vue中最后还要加上watch，求指点一二

**Comment by ciqulover** [comment]
路由如果改变，说明文章改变了，要重新读区数据和用hightlightjs渲染的

**Comment by rudyxu1102** [comment]
谢谢回答，博主的my-canvas组件好炫酷，好想学，有没有什么网站分享一下

**Comment by ciqulover** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API
其实关键是创意吧，可以看看codepen上的
https://codepen.io/

**Comment by rudyxu1102** [comment]
感谢
@ycwalker
