### ISSUE TITLE
npm run dev 热加载不起作用？

### ISSUE THREAD

**Issue by zhenizhui** [ycwalker/CMS-of-Blog#2]
你好，请教一个问题。

运行了`npm run dev` 截图如下

![qq 20161001095458](https://cloud.githubusercontent.com/assets/13503884/19010996/a87edf1c-87bd-11e6-8096-57ff0c4939f8.png)

是哪里出错了吗？访问localhost:8080 报404

**Comment by ciqulover** [comment]
这是因为你在8080端口下访问的是index.html, 然而默认文件中只有index.jade。 这时候应该运行node服务器 `npm run server` , 打开3000端口。 8080端口是热加载的，需要在线转换一下index.jade到index.html(如果是webstorm，可以安装jade插件实时转换)，放在项目目录中，8080端口就可以热加载调试了。

**Comment by zhenizhui** [comment]
的确如你所讲，要安装jade插件实时转换 :smile:

在热加载调试的时候还需要解决一个问题，请求的转发，代码如下

```
devServer: {
        historyApiFallback: true,
        noInfo: true,
        proxy: {
            '/': {
                target: 'http://localhost:3000/'
            }
        }
    }
```

thanks for you help !

**Comment by ciqulover** [comment]
感谢这个proxy！这个问题我也困扰了很久呢~

**Comment by Chirs-Evans** [comment]
你好,请教下不知道为什么热加载总是不行,没弄过,具体操作是什么呢~
![image](https://cloud.githubusercontent.com/assets/17941821/25220990/1be2ba2a-25e6-11e7-800a-8b93bb9a3e9d.png)
